spring:
  application:
    name: member-service

server:
  port: 9002
  servlet:
    context-path: /services

security:
  oauth2:
    client:
      client-id: member-service
      client-secret: member-service-secret
    resource:
      user-info-uri: http://localhost:9000/services/user
