spring:
  application:
    name: member-service
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://localhost:9411

server:
  port: 9002
  servlet:
    context-path: /services

security:
  oauth2:
    client:
      client-id: member-service
      client-secret: member-service-secret
    resource:
      user-info-uri: http://localhost:9000/services/user
